[package]
name = "ForensicsModule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forensic-rs = "0.1.6"
frnsc-liveregistry-rs = "0.1.0"
hex = "0.4.3"
ascii_converter = "0.3.0"
